# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: scap-security-guide.spec

# add or remove files that should be synced
synced_files:
    - scap-security-guide.spec
    - .packit.yaml

# name in upstream package repository/registry (e.g. in PyPI)
upstream_package_name: scap-security-guide
# downstream (Fedora) RPM package name
downstream_package_name: scap-security-guide

actions:
  post-upstream-clone: "wget https://src.fedoraproject.org/rpms/scap-security-guide/raw/rawhide/f/scap-security-guide.spec -O scap-security-guide.spec"


# TODO: Remove the "jobs" key as soon as F34 is out
# Build doesn't pass (expectedly) on F32
jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-development
  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-development
