# platform = multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = medium
# disruption = medium
- name: "Read system commands directories without root ownership"
  command: "find -L /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin ! -user root -type d"
  register: system_commands_dirs_not_owned_by_root
  changed_when: False
  failed_when: False
  check_mode: no

- name: "Set ownership of system libraries to root"
  file:
    path: "{{ item }}"
    owner: "root"
  with_items: "{{ system_commands_dirs_not_owned_by_root.stdout_lines }}"
  when: system_commands_dirs_not_owned_by_root.stdout_lines | length > 0
